ALTER TABLE "Competition" ADD COLUMN "fullSeconds" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Competition" ADD COLUMN "maxSeconds" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Competition" ADD COLUMN "floorPercent" INTEGER NOT NULL DEFAULT 50;

ALTER TABLE "Competition" DROP COLUMN "speedBands";
