export const ACTION_LABELS = {
  APPROVE_MEMBER: "قبول طلب",
  REJECT_MEMBER: "رفض طلب",
  DELETE_MEMBER: "حذف طلب",
  RESTORE_MEMBER: "استرجاع عضو",
  DELETE_USER: "حذف حساب",
  RESTORE_USER: "استرجاع حساب",
  EXPORT_DATA: "تصدير بيانات",
  UPDATE_BOOKING: "تعديل بطاقة",
  SET_MATCH_FORFEIT: "تسجيل انسحاب في مباراة",
  CLEAR_MATCH_FORFEIT: "إلغاء انسحاب في مباراة",
  ISSUE_RECEIPT: "إصدار وصل قبض",
  VOID_RECEIPT: "إلغاء وصل قبض",
  UPDATE_ADMIN_ACTIVITIES: "تحديد أنشطة مشرف",
  CREATE_MEMBER_MANUAL: "إضافة عضو يدوياً",
  CREATE_PERSON: "إضافة شخص يدوياً",
  UPDATE_PERSON: "تعديل بيانات شخص",
  IMPORT_PEOPLE: "استيراد أشخاص من ملف",
  ADD_MEMBERSHIP: "إضافة اشتراك",
  RESET_MEMBER_PASSWORD: "إعادة تعيين كلمة مرور عضو",
  CHANGE_OWN_PASSWORD: "تغيير كلمة مرور شخصية",
  CREATE_ADMIN: "إنشاء حساب مشرف",
  DELETE_ADMIN: "حذف حساب مشرف",
  UPDATE_ADMIN_ROLE: "تغيير صلاحية مشرف",
  CREATE_EXPENSE_TAG: "إنشاء تصنيف",
  UPDATE_EXPENSE_TAG: "تعديل تصنيف",
  DELETE_EXPENSE_TAG: "حذف تصنيف",
  CREATE_PAYMENT_METHOD: "إنشاء طريقة دفع",
  UPDATE_PAYMENT_METHOD: "تعديل طريقة دفع",
  REORDER_PAYMENT_METHOD: "ترتيب طرق الدفع",
  CREATE_ACTIVITY: "إنشاء نشاط",
  UPDATE_ACTIVITY: "تعديل نشاط",
  PUBLISH_ACTIVITY: "نشر نشاط",
  UNPUBLISH_ACTIVITY: "إخفاء نشاط",
  OPEN_ACTIVITY_REGISTRATION: "فتح التسجيل في نشاط",
  CLOSE_ACTIVITY_REGISTRATION: "إغلاق التسجيل في نشاط",
  DUPLICATE_ACTIVITY: "نسخ نشاط",
  DELETE_ACTIVITY: "حذف نشاط",
  CREATE_TEAM: "إنشاء فريق",
  UPDATE_TEAM: "تعديل فريق",
  DELETE_TEAM: "حذف فريق",
  CREATE_MATCH: "إضافة مباراة",
  DELETE_MATCH: "حذف مباراة",
  ENTER_MATCH_RESULT: "إدخال نتيجة مباراة",
  CREATE_GROUP: "إنشاء مجموعة",
  UPDATE_GROUP: "تعديل مجموعة",
  DELETE_GROUP: "حذف مجموعة",
  SEND_BROADCAST: "إرسال إشعار جماعي",
  SEND_BROADCAST_TO_EVERYONE: "إرسال إشعار للجميع",
  CHASE_WAITING_REQUEST: "تذكير بطلب معلق",
  APPROVE_TEAM_JOIN: "قبول طلب انضمام لفريق",
  DELETE_DONATION: "حذف تبرع نهائياً",
  ATTACH_MEMBER_ACCOUNT: "إنشاء حساب لعضو",
  CHANGE_ACCOUNT_PHONE: "تغيير رقم حساب عضو",
  CREATE_EXPENSE: "إضافة مصروف",
  UPDATE_EXPENSE: "تعديل مصروف",
  DELETE_EXPENSE: "حذف مصروف",
  UPDATE_MEMBER: "تعديل بيانات عضو",
  REMOVE_MEMBER_PHOTO: "حذف صورة عضو",
  LOCK_MEMBER_PHOTO: "منع عضو من تغيير صورته",
  UNLOCK_MEMBER_PHOTO: "السماح لعضو بتغيير صورته",
  HIDE_SUPPORTER_NAME: "كتم اسم فاعل خير",
  SHOW_SUPPORTER_NAME: "إظهار اسم فاعل خير",
  UPDATE_MEMBER_PAYMENT: "تعديل مبلغ عضو",
  IMPORT_QUIZ_QUESTIONS: "استيراد أسئلة",
  CREATE_QUESTION_BANK: "إنشاء بنك أسئلة",
  RENAME_QUESTION_BANK: "تغيير اسم بنك أسئلة",
  DELETE_QUESTION_BANK: "حذف بنك أسئلة",
  SAVE_COMPETITION: "حفظ إعدادات المسابقة",
  START_COMPETITION: "إطلاق المسابقة",
  COPY_COMPETITION: "نسخ المسابقة",
  DELETE_COMPETITION: "حذف مسابقة",
  SET_QUIZ_PARTICIPANTS: "تحديد المشاركين في مسابقة",
  SET_QUIZ_ROUND_POOL: "تحديد أسئلة جولة",
  FILL_QUIZ_ROUNDS: "توزيع الأسئلة على الجولات",
  RESET_QUIZ_SCORES: "تصفير نقاط المسابقة",
  REOPEN_QUIZ_ATTEMPT: "إعادة فتح الأسئلة الفائتة لمشارك",
  VOID_QUIZ_SCORE: "إلغاء نقاط مشارك",
  RESTORE_QUIZ_SCORE: "إرجاع نقاط مشارك",
  RENEW_MEMBER: "تجديد عضوية",
  CREATE_AGE_GROUP: "إضافة عصر",
  UPDATE_AGE_GROUP: "تعديل اسم عصر",
  DELETE_AGE_GROUP: "حذف عصر",
  APPROVE_AGE_GROUP: "قبول عصر مقترح",
  CREATE_VILLAGE: "إضافة قرية",
  UPDATE_VILLAGE: "تعديل اسم قرية",
  DELETE_VILLAGE: "حذف قرية",
  ADMIN_UNREGISTER_ACTIVITY: "إلغاء تسجيل عضو في نشاط",
  REMOVE_TEAM_MEMBER: "إزالة لاعب من فريق",
  REASSIGN_AGE_GROUP: "نقل أعضاء إلى عصر آخر",
  CREATE_QUIZ_QUESTION: "إضافة سؤال ",
  UPDATE_QUIZ_QUESTION: "تعديل سؤال ",
  DELETE_QUIZ_QUESTION: "حذف سؤال ",
  SEND_QUIZ_QUESTION: "إرسال سؤال ",
  UPDATE_QUIZ_SETTINGS: "تعديل إعدادات الأسئلة",
  APPROVE_DONATION: "قبول تبرع",
  REJECT_DONATION: "رفض تبرع",
  UPDATE_DONATION: "تعديل تبرع",
  CREATE_DONATION_MANUAL: "إضافة تبرع يدوياً",
  LINK_DONATION_MEMBER: "ربط تبرع بعضو",
  UNLINK_DONATION_MEMBER: "إلغاء ربط تبرع بعضو",
  APPROVE_ACTIVITY_REGISTRATION: "قبول تسجيل في نشاط",
  REJECT_ACTIVITY_REGISTRATION: "رفض تسجيل في نشاط",
  ADMIN_REGISTER_ACTIVITY: "تسجيل عضو في نشاط",
  OPEN_MVP_VOTE: "فتح تصويت أفضل لاعب",
  CLOSE_MVP_VOTE: "إغلاق تصويت أفضل لاعب",
  REOPEN_MVP_VOTE: "إعادة فتح تصويت أفضل لاعب",
  EXTEND_MVP_VOTE: "تمديد مدة تصويت أفضل لاعب",
  DELETE_MVP_VOTE: "حذف تصويت أفضل لاعب",
  GENERATE_MATCH_SCHEDULE: "توليد جدول المباريات",
  GENERATE_BRACKET_DRAW: "توليد قرعة الأدوار الإقصائية",
  SET_UP_TOURNAMENT: "إعداد البطولة",
  RESET_TOURNAMENT: "تصفير البطولة",
  GENERATE_BRACKET_SEMIS: "توليد نصف النهائي",
  GENERATE_BRACKET_NEXT_ROUND: "توليد الدور التالي",
  UPDATE_SETTINGS: "تعديل إعدادات الرابطة",
  ADMIN_LOGIN: "دخول مشرف",
  PROPOSE_SUSPENSION: "اقتراح إيقاف لاعب",
  APPROVE_SUSPENSION: "اعتماد إيقاف لاعب",
  DISMISS_SUSPENSION: "رفض اقتراح إيقاف",
  LIFT_SUSPENSION: "إلغاء إيقاف لاعب",
  CREATE_BOOKING: "تسجيل بطاقة",
  DELETE_BOOKING: "حذف بطاقة",
  ADD_TEAM_MEMBER: "إضافة لاعب إلى فريق",
} as const;

export type AuditAction = keyof typeof ACTION_LABELS;

export function auditActionLabel(action: string): string {
  return ACTION_LABELS[action as AuditAction] ?? action;
}
