import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ARABIC = /[؀-ۿ]/;

const KEPT_CLEAN = [
  "src/app/(member)/donate/page.tsx",
  "src/app/admin/dashboard/FilterSheet.tsx",
  "src/app/admin/dashboard/MemberDrawer.tsx",
  "src/app/admin/members/[id]/AccountPhoneForm.tsx",
  "src/app/admin/payments/DonationActions.tsx",
  "src/app/admin/payments/DonationEditForm.tsx",
  "src/app/admin/payments/LinkMemberPanel.tsx",
  "src/app/admin/payments/ManualDonationDialog.tsx",
  "src/app/admin/payments/ProofCard.tsx",
  "src/app/admin/payments/paymentTypes.ts",
  "src/app/admin/payments/donationProof.ts",
  "src/app/admin/payments/useDonationActions.ts",
  "src/app/admin/payments/MemberIdentity.tsx",
  "src/app/admin/members/[id]/page.tsx",
  "src/app/admin/activities/[id]/DetailsTab.tsx",
  "src/app/admin/activities/[id]/ConvertTournamentCard.tsx",
  "src/app/admin/activities/[id]/DeleteActivityCard.tsx",
  "src/app/admin/activities/[id]/ResetTournamentCard.tsx",
  "src/app/admin/activities/[id]/ActivityFinance.tsx",
  "src/app/admin/activities/[id]/LogTab.tsx",
  "src/app/admin/activities/[id]/page.tsx",
  "src/app/admin/activities/ActivityDatesEditor.tsx",
  "src/app/admin/activities/NewActivityDialog.tsx",
  "src/app/admin/activities/page.tsx",
  "src/app/admin/activities/ActivitiesHeader.tsx",
  "src/app/admin/activities/ActivitiesFilters.tsx",
  "src/app/admin/activities/FilterAxisRow.tsx",
  "src/app/admin/activities/ActivityChips.tsx",
  "src/components/ActivityRowBody.tsx",
  "src/components/PaymentInfoBanner.tsx",
  "src/components/admin/PaymentAccountList.tsx",
  "src/components/admin/PaymentAccountPicker.tsx",
  "src/app/admin/dashboard/RenewForm.tsx",
  "src/app/admin/payments/page.tsx",
  "src/components/admin/PaymentAccountRow.tsx",
  "src/app/membership/StepPayment.tsx",
  "src/app/membership/AccountChoice.tsx",
  "src/components/PaymentMethodChoice.tsx",
  "src/app/admin/activities/ActivityRow.tsx",
  "src/app/admin/activities/ActivitiesList.tsx",
  "src/app/admin/activities/ActivitiesSkeleton.tsx",
  "src/app/admin/activities/AttentionPanel.tsx",
  "src/app/admin/activities/AttentionRowCard.tsx",
  "src/app/admin/activities/AttentionOrder.tsx",
  "src/app/admin/activities/useAttentionActions.ts",
  "src/app/admin/activities/useActivitiesData.ts",
  "src/app/admin/activities/[id]/activityTabs.ts",
  "src/components/admin/WorkspaceTabs.tsx",
  "src/components/admin/CountBadge.tsx",
  "src/app/admin/WaitingRequests.tsx",
  "src/components/admin/SamePersonWarning.tsx",
  "src/components/admin/adminOrigin.tsx",
  "src/lib/adminBackLink.ts",
  "src/components/admin/shell/TopBar.tsx",
  "src/components/admin/shell/TabStrip.tsx",
  "src/components/admin/shell/SubTabStrip.tsx",
  "src/components/admin/shell/useStripScroll.ts",
  "src/components/admin/shell/AccountRow.tsx",
  "src/components/admin/shell/roleTone.ts",
  "src/app/admin/admins/page.tsx",
  "src/components/admin/tournament/tournamentTabs.ts",
  "src/app/admin/activities/ActivityRegistrationsPanel.tsx",
  "src/app/admin/activities/registrantFilter.ts",
  "src/app/admin/activities/registrationRecord.ts",
  "src/app/admin/activities/RegistrationRecord.tsx",
  "src/app/admin/activities/[id]/RegistrationsTab.tsx",
  "src/app/admin/activities/AddMemberToActivityForm.tsx",
  "src/app/admin/activities/activityTypes.ts",
  "src/app/admin/activities/PendingRegistrationCard.tsx",
  "src/app/admin/activities/ConfirmedRegistrantCard.tsx",
  "src/app/admin/activities/RegistrantIdentity.tsx",
  "src/app/admin/activities/PersonIdentity.tsx",
  "src/app/admin/activities/RegistrantSection.tsx",
  "src/app/api/admin/activities/[id]/detail/route.ts",
  "src/app/api/admin/activities/[id]/register",
  "src/app/api/admin/activities/[id]/days/schema.ts",
  "src/app/api/admin/activities/[id]/matches/route.ts",
  "src/app/api/admin/matches/[matchId]/mvp-vote/route.ts",
  "src/app/api/admin/activities/[id]/suspensions/schema.ts",
  "src/app/admin/receipts",
  "src/app/admin/settings",
  "src/app/api/admin/receipts",
  "src/app/api/donations/route.ts",
  "src/app/api/admin/matches/[matchId]/bookings",
  "src/app/api/admin/teams/[teamId]/members/route.ts",
  "src/app/api/teams/[teamId]/join",
  "src/app/api/admin/settings",
  "src/app/receipt",
  "src/components/receipt",
  "src/components/ActivityRegistrations.tsx",
  "src/components/admin/tournament/DaysTab.tsx",
  "src/components/admin/tournament/DayCard.tsx",
  "src/components/admin/tournament/daysTypes.ts",
  "src/components/admin/tournament/DayMatchResult.tsx",
  "src/components/admin/tournament/DayHeading.tsx",
  "src/components/admin/tournament/DayMatchTime.tsx",
  "src/components/admin/tournament/DayMatchRow.tsx",
  "src/lib/matchOutcome.ts",
  "src/components/admin/tournament/MatchCard.tsx",
  "src/components/admin/tournament/NewMatchForm.tsx",
  "src/components/admin/tournament/MatchCardActions.tsx",
  "src/components/admin/tournament/MatchDetailsForm.tsx",
  "src/components/admin/tournament/ResultForm.tsx",
  "src/components/admin/tournament/BracketPanel.tsx",
  "src/components/admin/tournament/BracketSuggestion.tsx",
  "src/components/admin/tournament/matchesState.ts",
  "src/components/admin/tournament/types.ts",
  "src/components/tournament/BracketTree.tsx",
  "src/components/tournament/BracketMatchCard.tsx",
  "src/components/tournament/BracketSide.tsx",
  "src/components/tournament/BracketConnectors.tsx",
  "src/lib/bracketLayout.ts",
  "src/components/tournament/MatchFixture.tsx",
  "src/components/tournament/PlayerAvatar.tsx",
  "src/components/tournament/TeamsGrid.tsx",
  "src/components/tournament/TeamCardHead.tsx",
  "src/components/tournament/SquadList.tsx",
  "src/lib/squad.ts",
  "src/components/tournament/TodayBand.tsx",
  "src/components/tournament/publicTypes.ts",
  "src/lib/fixtureTeams.ts",
  "src/lib/adminMatchesServer.ts",
  "src/lib/tournamentResetServer.ts",
  "src/app/api/admin/activities/[id]/tournament-reset/route.ts",
  "src/components/admin/tournament/TeamsTab.tsx",
  "src/components/admin/tournament/TeamCard.tsx",
  "src/components/admin/tournament/TeamSummary.tsx",
  "src/components/admin/tournament/TeamIdentityEditor.tsx",
  "src/components/admin/tournament/TeamRoster.tsx",
  "src/components/admin/tournament/AddPlayerRow.tsx",
  "src/components/admin/tournament/RosterRow.tsx",
  "src/components/admin/tournament/InlineRename.tsx",
  "src/components/ProofUpload.tsx",
  "src/components/admin/tournament/PlayersTab.tsx",
  "src/components/MemberCard.tsx",
  "src/components/SupportersTable.tsx",
  "src/components/PaidAmountRows.tsx",
  "src/components/SurplusVisibility.tsx",
  "src/app/(member)/leaderboard/page.tsx",
  "src/app/(member)/activities/[id]/MatchesPanel.tsx",
  "src/app/(member)/activities/[id]/tournamentPanels.tsx",
  "src/lib/bracketState.ts",
  "src/components/tournament/MatchResult.tsx",
  "src/components/tournament/matchCard/MatchEvents.tsx",
  "src/components/PaymentReceipts.tsx",
  "src/components/admin/shell/navTabs.ts",
  "src/components/admin/StatTile.tsx",
  "src/app/admin/supporters",
  "src/lib/matchEvents.ts",
  "src/lib/memberImportColumns.ts",
  "src/lib/memberImportCheck.ts",
  "src/lib/memberImportServer.ts",
  "src/lib/memberImportRun.ts",
  "src/lib/memberImportPasswords.ts",
  "src/app/admin/dashboard/MemberImportResult.tsx",
  "src/app/admin/dashboard/MemberSearch.tsx",
  "src/app/admin/dashboard/BareAccountsSection.tsx",
  "src/lib/memberImportTemplate.ts",
  "src/app/admin/dashboard/MemberImportDialog.tsx",
  "src/app/admin/dashboard/MemberImportUpload.tsx",
  "src/app/admin/dashboard/MemberImportReview.tsx",
  "src/app/admin/dashboard/MemberImportRow.tsx",
  "src/app/admin/dashboard/MemberImportBulkFill.tsx",
  "src/app/admin/dashboard/memberImportState.ts",
  "src/app/api/admin/people/import",
  "src/lib/memberImportBulk.ts",
  "src/lib/memberImportParse.ts",
  "src/app/api/admin/validate/route.ts",
  "src/app/api/user/me/route.ts",
  "src/lib/memberImportRow.ts",
  "src/lib/memberImportValues.ts",
  "src/lib/officialReceipt.ts",
  "src/lib/officialReceiptServer.ts",
  "src/lib/paymentReceiptServer.ts",
  "src/lib/receipts.ts",
  "src/lib/receiptsServer.ts",
  "src/app/admin/tools/toolLinks.ts",
  "src/app/admin/admins/page.tsx",
  "src/components/admin/shell/NewAccountForm.tsx",
  "src/app/api/admin/admins",
  "src/app/admin/expenses/page.tsx",
  "src/app/admin/quiz/ScoresPanel.tsx",
  "src/app/admin/quiz/ScoreRow.tsx",
  "src/app/admin/quiz/ScoreActions.tsx",
  "src/app/admin/quiz/scoreTypes.ts",
  "src/app/admin/quiz/scoreSearch.ts",
  "src/app/admin/quiz/CompetitionFields.tsx",
  "src/app/admin/quiz/CompetitionsSection.tsx",
  "src/app/admin/quiz/CompetitionWorkspace.tsx",
  "src/app/admin/quiz/competitionTabs.ts",
  "src/app/admin/quiz/StandingsPanel.tsx",
];

function sourceFiles(path: string): string[] {
  if (statSync(path).isFile()) return [path];
  return readdirSync(path, { withFileTypes: true }).flatMap((entry) => {
    const child = join(path, entry.name);
    if (entry.isDirectory()) return sourceFiles(child);
    if (!/\.tsx?$/.test(entry.name)) return [];
    if (/\.(test|ui\.test)\.tsx?$/.test(entry.name)) return [];
    return [child];
  });
}

function inlineArabic(path: string): number[] {
  return readFileSync(path, "utf8")
    .split("\n")
    .map((line, index) => (ARABIC.test(line) ? index + 1 : 0))
    .filter(Boolean);
}

describe("where the Arabic lives", () => {
  it("keeps every cleaned file free of inline text, so labels stay in the texts module", () => {
    const offenders = KEPT_CLEAN.flatMap(sourceFiles)
      .map((path) => ({ path, lines: inlineArabic(path) }))
      .filter((file) => file.lines.length > 0)
      .map((file) => `${file.path}:${file.lines.join(",")}`);

    expect(offenders).toEqual([]);
  });

  it("names nothing that has left the tree", () => {
    expect(() => KEPT_CLEAN.forEach((path) => statSync(path))).not.toThrow();
  });
});
