export const activityPage = {
  openBadge: "التسجيل مفتوح",
  closedBadge: "مغلق",
  notFound: "لم نجد هذا النشاط.",
  backToActivities: "الأنشطة",
  pageTitle: "النشاط",
  loading: "جاري التحميل...",
  participants: "مشارك",
  joinWhatsapp: "انضم كمتطوع الآن — واتساب",
  signUpCta: "سجّل الآن — أنشئ حسابك للمشاركة",
  haveAccount: "لديك حساب؟ تسجيل الدخول",
  supportCta: "ادعم هذا النشاط",
  supportersHeading: "داعمو هذا النشاط",
  supportersEmpty: "لم يدعم أحد هذا النشاط بعد، كن أول داعم له.",
} as const;
