export const activityReport = {
  navLabel: "تقرير الأنشطة",
  from: "من",
  to: "إلى",
  run: "اعرض التقرير",
  print: "اطبع",
  exportCsv: "تصدير",
  span: (from: string, to: string) => `من ${from} إلى ${to}`,
  ouguiya: (amount: number) => `${amount} أوقية`,
  general: "بلا نشاط",
  generalNote: "ما لم يُربط بنشاط، رسوم الانتساب والدعم العام والمصاريف العامة.",
  empty: "لا حركة مالية في هذه الفترة",
  activity: "النشاط",
  income: "دخل",
  spending: "صرف",
  balance: "الرصيد",
  total: "المجموع",
  surplus: "فائض",
  deficit: "عجز",
  even: "متعادل",
  spendingByTag: "الصرف حسب الوسم",
  incomeByTag: "الدخل حسب الوسم",
  receipts: "الوصولات",
  noReceipts: "لا وصولات مرقّمة في هذه الفترة",
  reconciles: (income: number, spending: number) =>
    `يطابق التقرير المالي لنفس الفترة، دخل ${income} أوقية وصرف ${spending} أوقية`,
} as const;
