import { countedNoun, MATCHES } from "../arabicPlural";
export const activityForm = {
  natures: {
    normal: "نشاط عادي",
    tournament: "بطولة",
    volunteer: "حملة تطوعية",
  },
  natureHeading: "نوع النشاط",
  titlePlaceholder: "عنوان النشاط",
  descriptionPlaceholder: "الوصف",
  from: "من",
  to: "إلى",
  capacityPlaceholder: "السعة القصوى (اختياري)",
  whatsappPlaceholder: "رابط مجموعة الواتساب — https://chat.whatsapp.com/...",
  tournamentLogo: "شعار البطولة",
  activityPhoto: "صورة النشاط",
  submit: "إضافة",
  dialogTitle: "إضافة نشاط",
  registrationOpen: "التسجيل مفتوح",
  autoApprove: "قبول التسجيل تلقائياً",
  showScorersAndCards: "عرض الهدافين والبطاقات الحمراء",
  showScorersAndCardsHint: "عند الإطفاء تبقى النتيجة ورجل المباراة والمجريات.",
  detailsHeading: "تفاصيل النشاط",
  title: "العنوان",
  description: "الوصف",
  capacity: "السعة",
  noCapacity: "بدون حد",
  whatsappLink: "رابط الواتساب",
  save: "حفظ التفاصيل",
  saved: "تم حفظ التفاصيل",
  photoSaved: "تم حفظ الصورة",
  datesHeading: "التواريخ",
} as const;

export const convertCampaign = {
  heading: "وضع الحملة التطوعية",
  hint: "مجموعة واتساب يلتحق بها المتطوعون",
  convert: "تحويل إلى حملة تطوعية",
  confirm: "تأكيد التحويل",
  unconvert: "إلغاء وضع الحملة",
  dialogTitle: "تحويل إلى حملة تطوعية",
  whatsappLabel: "رابط مجموعة الواتساب",
  pendingHeading: (n: number) =>
    n === 1 ? "طلب تسجيل واحد ما يزال في الانتظار" : `${n} طلبات تسجيل ما تزال في الانتظار`,
  pendingHint: "الحملة التطوعية لا تدير طلبات التسجيل، فاحسم ما ينتظر قبل التحويل.",
  acceptAll: "اقبلها كلها",
  rejectAll: "ارفضها كلها",
  converted: "أصبح النشاط حملة تطوعية",
  unconverted: "لم يعد النشاط حملة تطوعية",
} as const;

export const activityRow = {
  pendingChip: (n: number) => `${n} في الانتظار`,
  joinRequestChip: (n: number) => `${n} طلب انضمام`,
  filters: {
    any: "الكل",
    typeAxis: "النوع",
    stateAxis: "التسجيل",
    stageAxis: "المرحلة",
    tournament: "بطولات",
    volunteer: "حملات",
    plain: "عادية",
    open: "مفتوح",
    closed: "مغلق",
    current: "جارية وقادمة",
    finished: "منتهية",
    heading: "تصفية",
    chip: (label: string, n: number) => `${label} ${n}`,
    pick: (axis: string, label: string) => `${axis}: ${label}`,
  },
  regions: {
    work: "ما يحتاج انتباهك",
    filters: "تصفية الأنشطة",
    list: "قائمة الأنشطة",
  },
  loadingList: "جارٍ تحميل الأنشطة",
  sections: {
    current: "جارية وقادمة",
    finished: (n: number) => `منتهية (${n})`,
  },
  registeredOf: (registered: number, capacity: number) => `${registered} من ${capacity}`,
  rowMenu: (title: string) => `خيارات ${title}`,
  searchPlaceholder: "بحث باسم النشاط...",
  add: "إضافة نشاط",
  emptyList: "لا توجد أنشطة بعد",
  emptySearch: "لا يطابق أي نشاط هذا البحث",
  addFirst: "أضف أول نشاط",
  draftChip: "مسودة",
  publish: "نشر النشاط",
  unpublish: "إخفاء من صفحات الأعضاء",
  openRegistration: "فتح التسجيل",
  closeRegistration: "إغلاق التسجيل",
  duplicate: "نسخ النشاط",
  duplicated: "أُنشئت نسخة كمسودة",
  pickRow: (title: string) => `تحديد ${title}`,
  selectMode: "تحديد",
  picked: (n: number) => `${n} محدَّد`,
  bulkClose: "إغلاق التسجيل",
  bulkDelete: "حذف",
  bulkClear: "إلغاء التحديد",
  bulkFailed: (n: number) => `تعذّر تنفيذ ${n} منها`,
  bulkDeleteTitle: "حذف الأنشطة المحدَّدة",
  bulkDeleteMessage: (n: number) =>
    `سيُحذف ${n} نشاطاً نهائياً، ومعها تسجيلات الأعضاء وفرقها ومبارياتها.`,
  bulkDeleteConfirm: "حذف نهائي",
  arrangeLink: "ترتيب الظهور",
  arrangeTitle: "ترتيب ظهور الأنشطة",
  arrangeNote:
    "المرحلة تُقرَّر أولاً: الجاري ثم القادم ثم المنتهي. الأسهم ترتّب النشاط داخل مرحلته فقط.",
  arrangeBack: "الأنشطة",
  arrangeEmpty: "لا توجد أنشطة لترتيبها",
  stages: {
    live: "جارية الآن",
    awaiting: "لم تنته بعد",
    upcoming: "قادمة",
    undatedOpen: "بلا تاريخ — التسجيل مفتوح",
    undatedClosed: "بلا تاريخ — التسجيل مغلق",
    finished: "منتهية",
  },
  tournamentChip: "بطولة",
  volunteerChip: "حملة تطوعية",
  closedChip: "التسجيل مغلق",
  manageTournament: "إدارة البطولة",
  moveUp: (title: string) => `تقديم ${title} في الترتيب`,
  moveDown: (title: string) => `تأخير ${title} في الترتيب`,
} as const;

export const activityStandingTexts = {
  startsToday: "يبدأ اليوم",
  startsTomorrow: "يبدأ غداً",
  startsIn: (days: number) =>
    days === 2 ? "يبدأ بعد يومين" : days <= 10 ? `يبدأ بعد ${days} أيام` : `يبدأ بعد ${days} يوماً`,
  running: "جارٍ الآن",
  awaiting: (count: number) => `بقيت ${countedNoun(count, MATCHES)}`,
  groupStage: "دور المجموعات",
  finished: "انتهى",
  notScheduled: "غير مبرمج بعد",
} as const;

export const tournamentSetup = {
  shapeHeading: "نوع المباراة",
  shapes: {
    FOOTBALL: "مباراة كرة قدم",
    SERIES: "سلسلة جولات · شطرنج، ضامة، ورق، بلاي ستيشن",
  },
  formatHeading: "نظام البطولة",
  formats: {
    KNOCKOUT: "خروج المغلوب مباشرة",
    GROUPS_THEN_KNOCKOUT: "مجموعات ثم خروج المغلوب",
  },
  squadHeading: "عدد لاعبي الفريق",
  singles: "بطولة فردية",
  minTeamSize: "الحد الأدنى",
  maxTeamSize: "الحد الأقصى",
  organisedByHomeVillage: "بطولة من تنظيم التاكلالت",
  outsidePlayerLimit: "الحد الأقصى للاعبين من خارج التاكلالت",
  shapeLocked: "النظام والنوع أُقفلا بعد إنشاء أول مباراة",
  squadLocked: "حجم الفريق أُقفل بعد انطلاق البطولة",
} as const;
