export const activityRegistration = {
  joinRequested: "تم إرسال طلب الانضمام — بانتظار موافقة المشرف",
  requestCancelled: "تم إلغاء الطلب",
  volunteered: "تم تسجيلك كمتطوع",
  registered: "تم التسجيل في النشاط",
  cancel: "إلغاء",
  retry: "إعادة المحاولة",
  volunteer: "تطوع",
  register: "سجّل",
  closed: "التسجيل مغلق",
  full: "اكتمل العدد",
  lastRejection: (reason: string) => `سبب الرفض السابق: ${reason}`,
  chooseTeamAtRegistration: "اختر فريقك",
  noTeamYet: "بلا فريق بعد",
  chosenTeamPending: (teamName: string) => `اخترت ${teamName} — تنضم إليه عند قبول تسجيلك`,
} as const;
