export const activityAttention = {
  title: "يحتاج انتباهك",
  empty: "لا شيء ينتظرك في الأنشطة",
  oldestFirst: "الأقدم أولاً",
  newestFirst: "الأحدث أولاً",
  order: "ترتيب ما ينتظر",
  show: "عرض",
  hide: "إخفاء",
  kinds: {
    join: "طلب انضمام إلى فريق",
    registration: "طلب تسجيل في نشاط",
    suspension: "عقوبة مقترحة",
  },
  group: (label: string, n: number) => `${label} (${n})`,
  today: "اليوم",
  waiting: (days: number) => `منذ ${days} يوم`,
  open: "فتح",
  accept: "قبول",
  refuse: "رفض",
  acceptRow: (who: string) => `قبول ${who}`,
  refuseRow: (who: string) => `رفض ${who}`,
  openRow: (who: string) => `فتح ${who}`,
  accepted: "تم القبول",
  refused: "تم الرفض",
} as const;
