export const activityRegistrants = {
  add: "تسجيل عضو يدوياً",
  search: "ابحث بالاسم أو الهاتف...",
  noMatch: "لا يوجد عضو مطابق",
  more: (count: number) => `و${count} غيرهم — حدّد بحثك أكثر`,
  allRegistered: "كل الأعضاء مسجلون في هذا النشاط",
  pending: "طلبات قيد المراجعة",
  confirmed: "مسجَّلون مؤكَّدون",
  noneConfirmed: "لا يوجد مسجلون مؤكَّدون بعد",
  unknownPhone: "غير معروف",
  remove: "إزالة",
  noTeam: "بلا فريق",
  searchRegistrants: "ابحث في المسجلين بالاسم أو الهاتف أو الفريق...",
  searchPlayers: "ابحث في المسجلين بالاسم أو الهاتف...",
  // The two searches on this tab do opposite things, so each says which it is.
  addSearchLabel: "البحث عن عضو لتسجيله",
  searchLabel: "البحث في المسجلين",
  noneMatch: "لا يوجد مسجل مطابق",
  filterByTeam: "تصفية حسب الفريق",
  allTeams: "كل الفرق",
  searchToBegin: "اكتب اسماً أو رقم هاتف للبحث عن عضو",
  alreadyRegistered: "مسجَّل بالفعل",
  addedBySelf: "سجّل نفسه",
  addedByAdmin: (admin: string) => `أضافه ${admin}`,
  addedByAdminUnnamed: "أضافه مشرف",
  addedUnknown: "غير معروف",
  sortByRequested: "ترتيب حسب تاريخ الطلب",
  newestFirst: "الأحدث أولاً",
  oldestFirst: "الأقدم أولاً",
  candidateDetail: (village: string | null, age: string | null) =>
    [village, age].filter(Boolean).join(" · "),
  viewProof: "عرض إثبات الدفع",
  rejectReason: "سبب الرفض (اختياري)...",
  confirmReject: "تأكيد الرفض",
  cancel: "إلغاء",
  accept: "قبول",
  reject: "رفض",
} as const;

export const registrationStatusLabels: Record<string, string> = {
  PENDING: "قيد الانتظار",
  ACTIVE: "مؤكَّد",
  REJECTED: "مرفوض",
};
