export const adminAccounts = {
  title: "حسابات المشرفين",
  confirmDelete: "هل أنت متأكد من حذف هذا الحساب؟",
  addTitle: "إضافة مشرف جديد",
  username: "اسم المستخدم",
  password: "كلمة المرور",
  scopeHint:
    "لحصر مشرف في أنشطة بعينها، أنشئ الحساب ثم اضغط «تحديد الأنشطة» في صفّه — تتحول صلاحيته تلقائياً إلى أنشطة محددة فقط.",
  submit: "إضافة",
  submitting: "...",
  you: "أنت",
  changeRole: "تغيير الصلاحية",
  applyRole: "تطبيق",
  applyingRole: "...",
  ownRoleLocked: "لا تُغيَّر صلاحيتك من هنا",
  cancelRole: "إلغاء",
  scope: "تحديد الأنشطة",
  remove: "حذف",
  lastLogin: "آخر دخول",
  neverSignedIn: "لم يسجّل الدخول بعد",
  moreDetails: "تفاصيل الحساب",
  createdAt: "أُنشئ في",
  lastLoginIp: "عنوان آخر دخول",
} as const;
