export const daysTab = {
  addRestHere: "أضف يوم راحة هنا",
  loadFailed: "فشل تحميل الأيام",
  needStartDate: "حدد تاريخ بداية البطولة أولاً",
  countedFromStart: "الأيام تُحسب من تاريخ البداية، ويُحسب تاريخ النهاية تلقائياً من عدد الأيام.",
  openActivity: "فتح تفاصيل النشاط",
  endFromLastDay: "تاريخ النهاية يُحسب تلقائياً من آخر يوم.",
  notifyOnMove: "إشعار اللاعبين والمتابعين عند تحريك الجدول",
  restAdded: "أُضيف يوم راحة وتحرّك ما بعده يوماً",
  dayChanged: "تم تغيير اليوم",
  dayRemoved: "حُذف اليوم وتحرّك ما بعده يوماً",
  timeChanged: "تغيّر الوقت",
  matchDayAppended: "أُضيف يوم في النهاية",
  addMatchDay: "إضافة يوم مباريات",
  restDayAppended: "أُضيف يوم راحة في النهاية",
  addRestDay: "إضافة يوم راحة",
  unscheduled: (count: number) => `مباريات بلا يوم (${count})`,
  pickDayLabel: "اختيار اليوم",
  pickDay: "اختر اليوم...",
  dayNumber: (position: number) => `اليوم ${position}`,
  dayOption: (position: number, label: string) => `${daysTab.dayNumber(position)} — ${label}`,
  dayLocked: "اليوم أُقفل لأن فيه مباريات",
  makeMatchDay: "جعله يوم مباريات",
  makeRestDay: "جعله يوم راحة",
  removeDay: "حذف اليوم",
  doubleBooked: (names: string) => `يلعب مرتين في نفس اليوم: ${names}`,
  finished: "انتهت",
  matchTime: "وقت المباراة",
  changeTime: "تغيير وقت المباراة",
  noTime: "بلا وقت",
  scheduled: "جُدولت المباراة",
  schedule: "جدولة",
} as const;
