export const discipline = {
  tab: "الانضباط",
  rulesTitle: "قواعد الإيقاف",
  yellowsForBan: "عدد البطاقات الصفراء التي تقترح إيقافاً",
  redBanMatches: "عدد مباريات الإيقاف بعد البطاقة الحمراء",
  saveRules: "حفظ القواعد",
  rulesSaved: "حُفظت القواعد",
  proposalsTitle: "اقتراحات بانتظار الاعتماد",
  approve: "اعتماد",
  dismiss: "رفض",
  activeTitle: "إيقافات نافذة",
  lift: "إلغاء الإيقاف",
  historyTitle: "إيقافات منتهية",
  proposeTitle: "إيقاف لاعب",
  pickPlayer: "اختر لاعباً...",
  scopeLabel: "مدة الإيقاف",
  scopeMatches: "عدد مباريات",
  scopeDays: "حتى تاريخ",
  scopeIndefinite: "نهائي",
  matchesCount: "عدد المباريات",
  untilDate: "تاريخ نهاية الإيقاف",
  notePlaceholder: "السبب (اختياري)",
  propose: "اقتراح الإيقاف",
  empty: "لا إيقافات ولا اقتراحات في هذه البطولة",
  system: "النظام",
  systemProposal: "اقتراح النظام",
  proposedBy: (name: string) => `اقترحه ${name}`,
  reasons: {
    RED_CARD: "بطاقة حمراء",
    YELLOW_CARDS: "تراكم البطاقات الصفراء",
    CONDUCT: "سلوك",
  },
  suspendedBadge: "موقوف",
  hiddenSuspended: (names: string) => `موقوفون عن هذه المباراة: ${names}`,
  remaining: (matches: string) => `متبقي ${matches}`,
  until: (date: string) => `حتى ${date}`,
  indefinite: "إيقاف نهائي",
  expired: "انتهت المدة",
} as const;
