export const filterSheet = {
  title: "تصفية القائمة",
  byVillage: "تصفية حسب القرية",
  age: "العصر",
  byAge: "تصفية حسب العصر",
  allAges: "كل الأعصار",
  method: "طريقة الدفع",
  byMethod: "تصفية حسب طريقة الدفع",
  allMethods: "كل طرق الدفع",
  paid: "المبلغ المدفوع",
  byPaid: "تصفية حسب المبلغ المدفوع",
  allAmounts: "كل المبالغ",
  paidFull: "دفع كامل",
  paidPartial: "دفع ناقص",
  paidNone: "لم يدفع",
  membershipYear: "سنة العضوية",
  byYear: "تصفية حسب سنة العضوية",
  allYears: "كل السنوات",
  yearOption: (year: number) => `عضوية ${year}`,
  requestDate: "تاريخ الطلب",
  membershipOf: (year: number) => `عضوية ${year}`,
  clear: "إزالة التصفية",
  done: "تم",
} as const;
