export const financeReport = {
  from: "من",
  to: "إلى",
  run: "اعرض التقرير",
  print: "اطبع",
  span: (from: string, to: string) => `من ${from} إلى ${to}`,
  ouguiya: (amount: number) => `${amount} أوقية`,
  moneyDetail: (income: number, spending: number) => `دخل ${income} أوقية، صرف ${spending} أوقية`,
  splitDetail: (fees: number, support: number) => `انتساب ${fees} أوقية، دعم ${support} أوقية`,
  monthByMonth: "شهراً بشهر",
  month: "الشهر",
  income: "دخل",
  spending: "صرف",
  net: "الصافي",
  incomeByTag: "الدخل حسب الوسم",
  spendingByTag: "الصرف حسب الوسم",
  tagTotal: "مجموع الوسوم",
  tagsOverlap: "المبلغ الواحد يُحتسب تحت كل وسم يحمله، لذلك يتجاوز المجموع هنا الإجمالي",
} as const;
