export const manualDonation = {
  title: "تسجيل تبرع يدوياً",
  intro: "لتبرع تلقيته خارج التطبيق نقداً أو تحويلاً — يُحتسب مباشرة في لوحة شرف المتبرعين.",
  donorPhoto: "صورة المتبرع (اختياري)",
  proof: "إثبات الدفع (اختياري — يمكن إضافته لاحقاً)",
  donorName: "اسم المتبرع",
  donorNameFromAccount: "الاسم مأخوذ من حساب العضو المرتبط",
  phone: "رقم الهاتف (اختياري)",
  amount: "المبلغ (MRU)",
  paymentMethod: "طريقة الدفع",
  methodUnset: "غير محددة",
  destination: "وجهة الدعم",
  account: "الحساب المرتبط (اختياري)",
  accountHint: "اربطه بحساب العضو ليظهر باسمه على اللوحة",
  clearAccount: "إلغاء الربط",
  submit: "تسجيل التبرع",
} as const;
