export const manualAdd = {
  title: "إضافة شخص يدوياً",
  personStep: "بيانات الشخص",
  paymentStep: "الاشتراك",
  personSubmit: "حفظ الشخص",
  paymentSubmit: "تسجيل الاشتراك",
  skipPayment: "بدون اشتراك الآن",
  personSaved: "تم حفظ الشخص. سجّل اشتراكه الآن أو لاحقاً من قائمة الأشخاص بلا اشتراك.",
  phoneUnknown: "رقم الهاتف غير معروف — يُضاف لاحقاً",
  accountPhoneLabel: "رقم هاتف الحساب",
  accountPhoneHint: "إن لم يوجد حساب بهذا الرقم، سيُنشأ حساب جديد تلقائياً بكلمة مرور مؤقتة",
  fullNameLabel: "الاسم الكامل",
  photoLabel: "صورة العضو (اختياري)",
  photoPick: "انقر لإرفاق صورة العضو (اختياري)",
  proofLabel: "صورة إثبات الدفع (اختياري)",
  proofPick: "انقر لإرفاق صورة (اختياري)",
  imageChange: "انقر لتغيير الصورة",
  uploading: "جاري الرفع...",
  manageAgeGroups: "إدارة الأعصار",
  paymentMethodLabel: "طريقة الدفع",
  pick: "اختر...",
  paidAmountLabel: "المبلغ المسدد (أوقية) — اختياري",
  statusLabel: "حالة العضوية",
  statusActive: "مقبول مباشرة",
  statusPending: "قيد الانتظار",
  submit: "إنشاء العضو",
  submitUploading: "جاري رفع الصورة...",
  created: "تمت الإضافة بنجاح",
  tempPasswordNote: "كلمة مرور الحساب الجديد — سلّمها للعضو",
  copy: "نسخ",
  addAnother: "إضافة شخص آخر",
} as const;
