export const matchLevelsSetup = {
  heading: "مستويات المباراة",
  matchLevel: "المباراة",
  levelNumber: (order: number) => `المستوى ${order}`,
  singular: "اسم الوحدة مفرداً",
  plural: "اسم الوحدة جمعاً",
  rules: "قواعد هذا المستوى",
  countedBy: "بم تُحسب وحداته",
  countedByOutcome: "بنتيجتها",
  countedByPoints: "بنقاطها",
  endsBy: "متى ينتهي",
  endsByCount: "بعدد وحدات",
  endsByTarget: "ببلوغ رقم",
  unitCount: "عدد الوحدات",
  target: "الرقم الذي ينهيه",
  deciderTarget: "رقم الوحدة الحاسمة",
  unsettled: "إن لم يُحسم",
  unsettledNever: "لا يقع",
  unsettledContinue: "تُستكمل وحدات حتى يتقدم أحدهما",
  unsettledDecider: "تُلعب وحدة حاسمة",
  unsettledDraw: "ينتهي متعادلاً",
  margin: "الفارق الذي يحسمه",
  continueUnits: "عدد وحدات الاستكمال",
  startingCredit: "الرصيد الابتدائي",
  creditWindow: "عدد الوحدات التي يُكتسب فيها الرصيد",
  addLevel: "إضافة مستوى",
  removeLevel: (order: number) => `حذف المستوى ${order}`,
  moveUp: (order: number) => `تقديم المستوى ${order}`,
  moveDown: (order: number) => `تأخير المستوى ${order}`,
  save: "حفظ المستويات",
  saved: "حُفظت مستويات المباراة",
  loadFailed: "تعذّر تحميل مستويات البطولة",
  none: "لا مستويات معرّفة بعد",
  moves: "الحركات المعرّفة",
  moveName: "اسم الحركة",
  moveToSelf: "ما تضيفه",
  moveFromOther: "ما تخصمه",
  moveLevel: "المستوى الذي تقع فيه",
  moveEndsUnit: "تنهي الوحدة التي تقع فيها",
  moveWorth: "العدد الذي تُحتسب به الوحدة",
  addMove: "إضافة حركة",
  removeMove: (name: string) => `حذف ${name}`,
  moveLine: (name: string, toSelf: string, fromOther: string) =>
    `${name} تضيف ${toSelf} وتخصم ${fromOther}`,
  moveEndsLine: "تنهي الوحدة",
  moveWorthLine: (worth: string) => `تُحتسب الوحدة بـ${worth}`,
  noMoves: "لا حركات معرّفة",
} as const;
