export const matchLevelsSetup = {
  heading: "مستويات المباراة",
  matchLevel: "المباراة",
  levelNumber: (order: number) => `المستوى ${order}`,
  singular: "اسم الوحدة مفرداً",
  plural: "اسم الوحدة جمعاً",
  rules: "قواعد هذا المستوى",
  ending: "كيف ينتهي",
  endingPlayAll: "تُلعب كل وحداته",
  endingFirstTo: "أول من يبلغ عدداً من الوحدات",
  endingFirstPast: "أول من يتجاوز مجموعاً",
  unitsPerParent: "عدد الوحدات",
  unitsToWin: "عدد الوحدات التي تنهيه",
  target: "المجموع الذي ينهيه",
  bothPastTarget: "إذا تجاوز الطرفان المجموع",
  higherTotal: "يفوز صاحب المجموع الأكبر",
  playOn: "تُلعب وحدة أخرى حتى يتقدم أحدهما",
  deciderTarget: "مجموع الوحدة الحاسمة",
  halvesPerUnit: "أنصاف الوحدة الفائزة",
  extendsWhenLevel: "يُمدَّد عند التعادل",
  extensionUnits: "عدد وحدات التمديد",
  startingCredit: "الرصيد الابتدائي",
  creditWindow: "عدد الوحدات التي يُكتسب فيها الرصيد",
  decision: "كيف تُسجَّل الوحدة",
  decisionOutcome: "فوز أو تعادل",
  decisionScore: "نقاط الطرفين",
  wonUnitWorth: "قيمة الوحدة الفائزة",
  doubledWorth: "قيمتها مضاعفة",
  doublesOnBlankOpponent: "تُضاعف إذا كان الخصم بلا نقاط",
  doublesOnRecoveredCredit: "تُضاعف إذا فاز طرف فقد رصيده",
  addLevel: "إضافة مستوى",
  removeLevel: (order: number) => `حذف المستوى ${order}`,
  moveUp: (order: number) => `تقديم المستوى ${order}`,
  moveDown: (order: number) => `تأخير المستوى ${order}`,
  save: "حفظ المستويات",
  saved: "حُفظت مستويات المباراة",
  loadFailed: "تعذّر تحميل مستويات البطولة",
  none: "لا مستويات معرّفة بعد",
  moves: "الحركات المعرّفة",
  moveName: "اسم الحركة",
  moveToSelf: "ما تضيفه",
  moveFromOther: "ما تخصمه",
  moveLevel: "المستوى الذي تُسجَّل فيه",
  moveAnyLevel: "أي مستوى",
  moveEndsUnit: "تنهي الوحدة التي تقع فيها",
  addMove: "إضافة حركة",
  removeMove: (name: string) => `حذف ${name}`,
  moveLine: (name: string, toSelf: string, fromOther: string) =>
    `${name} تضيف ${toSelf} وتخصم ${fromOther}`,
  moveEndsLine: "تنهي الوحدة",
  noMoves: "لا حركات معرّفة",
} as const;
