export const matchAdmin = {
  upcoming: "مباريات قادمة",
  results: "نتائج",
  newMatch: "مباراة جديدة",
  homeTeamPlaceholder: "الفريق المضيف...",
  awayTeamPlaceholder: "الفريق الضيف...",
  roundPlaceholder: "الجولة (اختياري)",
  venuePlaceholder: "الملعب (اختياري)",
  knockoutFlag: "مباراة خروج المغلوب (لا تُحتسب في ترتيب المجموعات)",
  addMatch: "إضافة المباراة",
  suggestSchedule: "اقترح جدول المباريات",
  pickBothTeams: "يجب اختيار الفريقين",
  confirmDeleteMatch: "هل تريد حذف هذه المباراة؟",
  reorderFailed: "خطأ في إعادة الترتيب",
  poolsReadyTitle: "كل المجموعات مكتملة!",
  poolsReadyHint: "يمكنك الآن توليد جدول مباريات دور المجموعات وتوزيعه على أيام البطولة.",
  generateGroupSchedule: "توليد جدول مباريات دور المجموعات",
  groupStageDoneTitle: "انتهى دور المجموعات!",
  groupStageDoneHint: "كل الفرق لعبت مبارياتها — يمكنك الآن توليد نصف النهائي من ترتيب المجموعتين.",
  generateSemis: "توليد نصف النهائي",
  suggestionTitle: "جدول الإقصاء المقترح",
  suggestionHint:
    "متصدر كل مجموعة يلاقي وصيف مجموعة أخرى، والفريقان من مجموعة واحدة لا يلتقيان إلا في النهائي.",
  suggestionValidate: "اعتماد الجدول",
  suggestionRedo: "إعادة الاعتماد",
  suggestionGroupStageOpen: "أكمل نتائج دور المجموعات ليُقترح الجدول.",
  suggestionWinner: "المتصدر",
  suggestionRunnerUp: "الوصيف",
  suggestionProblem: {
    notGrouped: "هذه البطولة ليست مقسّمة إلى مجموعات",
    groupCount: "عدد المجموعات يجب أن يكون 2 أو 4 أو 8 ليكتمل جدول الإقصاء",
    groupTooSmall: "كل مجموعة تحتاج فريقين على الأقل",
    unresolvedTie: "هناك تعادل تام في الترتيب — احسم القرعة قبل اعتماد الجدول",
  } as Record<string, string>,
  confirmSemis: "توليد نصف النهائي من ترتيب المجموعتين؟",
  bracketTwoGroups: "نصف النهائي والنهائي",
  bracketKnockout: "القرعة الإقصائية (شطرنج، بلايستيشن، أو أي نظام إقصاء مباشر)",
  knockoutLockedHint:
    "أكمل جميع نتائج دور المجموعات أولاً — ستظهر خيارات الدور الإقصائي هنا بعد انتهاء دور المجموعات.",
  crossSemisHint:
    "نصف نهائي متقاطع من ترتيب المجموعتين (الأول من كل مجموعة أمام الثاني من الأخرى)، ثم النهائي.",
  drawHint:
    "قرعة عشوائية بين كل الفرق/اللاعبين المسجَّلين — يجب أن يكون العدد 4 أو 8 أو 16 أو 32...",
  draw: "قرعة عشوائية",
  confirmDraw: "إجراء قرعة عشوائية بين جميع الفرق الحالية؟",
  redraw: "إعادة القرعة",
  confirmRedraw: "إعادة القرعة؟ تُحذف مباريات الدور الأول الحالية وتُسحب قرعة جديدة",
  regenerateSemis: "إعادة توليد نصف النهائي",
  confirmRegenerateSemis:
    "إعادة توليد نصف النهائي من ترتيب المجموعتين؟ تُحذف مباراتا نصف النهائي الحاليتان",
  nextRound: "توليد الدور التالي",
  confirmNextRound: "توليد الدور التالي من نتائج الدور الحالي؟",
  champion: "البطل:",
  enterResult: "أدخل النتيجة",
  editResult: "تعديل النتيجة",
  penaltiesShort: "ركلات ترجيح",
  knockoutBadge: "إقصائية",
  priorMeetings: "مواجهات سابقة:",
  upcomingShort: "قادمة",
  moveUp: "تقديم",
  moveDown: "تأخير",
  motm: "رجل المباراة:",
  hideMvp: "إخفاء التصويت",
  mvpVote: "أفضل لاعب",
  hideDetails: "إخفاء التفاصيل",
  editDetails: "تعديل التفاصيل",
  goalsHeading: "الأهداف",
  kindGoal: "هدف",
  kindPenalty: "جزاء",
  kindOwnGoal: "عكسي",
  unknownScorer: "مجهول",
  extraTimeHeading: "الوقت الإضافي",
  extraTimeToggle: "المباراة ذهبت إلى وقت إضافي",
  shootoutHeading: "ركلات الترجيح",
  shootoutHint: "سجّل الركلات بترتيبها — النتيجة تُحسب وحدها",
  kickScored: "سجّل",
  kickMissed: "أضاع",
  forfeitHeading: "انسحاب",
  forfeitHint: "تُحتسب النتيجة لصالح الفريق الفائز، ويخسر المنسحب أهدافه. البطاقات تبقى كما هي.",
  forfeitWinnerLabel: "الفريق الفائز",
  forfeitPickWinner: "اختر الفريق الفائز",
  forfeitAwarded: "النتيجة المحتسبة",
  forfeitKeptGoals: "أهداف المنسحب تبقى مسجلة هنا وحدها، ليمكن التراجع عن القرار.",
  saveResult: "حفظ النتيجة",
  goalless: "بدون أهداف بعد — النتيجة تُحسب من الأهداف المسجلة",
  cardsHeading: "البطاقات",
  yellowCard: "صفراء",
  redCard: "حمراء",
  minute: "الدقيقة",
  add: "إضافة",
  remove: "حذف",
  edit: "تعديل",
  saveEdit: "حفظ التعديل",
  cancelEdit: "إلغاء التعديل",
  editingGoal: "تعديل هدف",
  editingCard: "تعديل بطاقة",
  pickPlayer: "اختر لاعباً...",
  fieldTeam: "الفريق",
  fieldKind: "النوع",
  fieldScorer: "المسجل",
  fieldPlayer: "اللاعب",
  fieldCard: "البطاقة",
  fieldMinute: "الدقيقة",
  fieldOutcome: "النتيجة",
  minuteHint: "اتركها فارغة إن لم تكن معروفة",
  ownGoalHint: "المسجل يُختار من الفريق الآخر",
  addGoal: "إضافة الهدف",
  addCard: "إضافة البطاقة",
  addKick: "إضافة الركلة",
} as const;

export const standingsAdmin = {
  noTeams: "لا توجد فرق بعد",
  group: "مجموعة",
  noGroup: "بدون مجموعة",
  exportCsv: "تصدير الترتيب والنتائج",
  csvFileSuffix: "الترتيب-والنتائج",
  csvStandings: "الترتيب",
  csvResults: "النتائج",
  csvStandingsColumns: ["#", "الفريق", "لعب", "فاز", "تعادل", "خسر", "له", "عليه", "الفرق", "نقاط"],
  csvResultsColumns: ["الجولة", "المضيف", "النتيجة", "الضيف", "الملعب", "التاريخ"],
} as const;

export const statsAdmin = {
  scorers: "الهدافون",
  noGoals: "لا توجد أهداف مسجلة بعد",
  cards: "البطاقات",
  noCards: "لا توجد بطاقات مسجلة بعد",
  defense: "أفضل دفاع",
  noDefense: "لا توجد بيانات كافية بعد",
  motm: "رجل المباراة",
  noMotm: "لم يتم تحديد رجل مباراة بعد",
  teams: "الفرق",
  noStats: "لا توجد إحصائيات مسجلة بعد",
} as const;
