export const memberPage = {
  loading: "جاري التحميل...",
  notFound: "لم نجد هذا العضو.",
  backToMembers: "المستخدمون",
  backToActivity: "النشاط",
  backToAdminHome: "لوحة التحكم",
  back: "رجوع",
  cancel: "إلغاء",
  edit: "تعديل",
  account: "الحساب",
  groupPerson: "الشخص",
  groupMembership: "الاشتراك",
  groupParticipation: "المشاركة",
  groupRecord: "السجل",
  activities: (count: number) => `الأنشطة (${count})`,
  noActivities: "لم يشارك في أي نشاط",
  teams: (count: number) => `الفرق (${count})`,
  noTeams: "ليس في أي فريق",
  donations: (count: number) => `التبرعات (${count})`,
  noDonations: "لا توجد تبرعات",
  history: (count: number) => `سجل التغييرات (${count})`,
  noHistory: "لا توجد تغييرات مسجلة",
} as const;
