export const memberDrawer = {
  title: "تفاصيل الطلب",
  close: "إغلاق",
  paid: "المبلغ المسدد",
  fee: "رسوم الاشتراك",
  support: "مبلغ الدعم",
  totalPaid: "إجمالي ما دُفع",
  phone: "رقم الهاتف",
  phoneUnknown: "غير معروف",
  age: "العصر",
  method: "طريقة الدفع",
  membershipYear: "سنة العضوية",
  memberNumber: "رقم العضوية",
  requestDate: "تاريخ الطلب",
  requestTime: "وقت الطلب",
  proofTitle: "صورة الكابتير",
  proofAlt: "كابتير",
  proofZoom: "انقر للتكبير",
  addedByAdmin: "أُضيف يدوياً من طرف المشرف — لا يوجد إثبات دفع",
  fullProfile: "الملف الكامل",
} as const;
