export const membershipSummary = {
  title: "العضوية",
  year: "السنة",
  standing: "الحالة",
  toPayment: "افتح الدفعة",
  openOnPayments: "افتح هذه الدفعة في صفحة الدفعات",
  noPaymentYet: "لا توجد دفعة مسجلة لهذه السنة",
  recordPayment: "سجّل الدفعة",
  paymentTitle: "دفعة العضوية",
  noProof: "لا يوجد إثبات دفع على هذه العضوية",
  amount: "المبلغ",
  viewProof: "فتح الإثبات كاملاً",
  states: {
    NOT_A_MEMBER: "ليس عضواً",
    APPLIED: "طلب قيد المراجعة",
    APPLICATION_REFUSED: "لم يُقبل الإثبات",
    UP_TO_DATE: "عضو لهذه السنة",
    BEHIND: "لم يجدّد لهذه السنة",
    ENDED: "عضوية منتهية",
  },
} as const;
