export const memberForm = {
  fullNameLabel: "الاسم الكامل (بالحروف العربية)",
  fullNamePlaceholder: "أدخل اسمك الكامل بالعربية",
  arabicOnly: "يرجى الكتابة بالحروف العربية فقط",
  phoneLabel: "رقم الهاتف",
  phoneAccountNote: "رقم حسابك — لتغييره تواصل مع المشرف",
  phoneHint: "8 أرقام — يبدأ بـ 2 أو 3 أو 4",
  ageLabel: "العصر",
  agePlaceholder: "اختر العصر...",
  addAge: "+ إضافة عصر جديد",
  newAgePlaceholder: "اكتب اسم العصر...",
  addAgeAction: "إضافة",
  addAgeNote: "العصر الجديد يظهر لك وحدك حتى يوافق عليه المشرف",
  next: "التالي",
} as const;
