export const memberImportDialog = {
  title: "إضافة مجموعة من ملف",
  uploadStep: "اختر الملف",
  reviewStep: "مراجعة السطور",
  pickFile: "انقر لاختيار ملف CSV",
  reading: "جاري قراءة الملف...",
  downloadTemplate: "تحميل نموذج الملف",
  templateNote: "احفظ الملف من Excel بصيغة CSV قبل رفعه",
  fileNotCsv: "يرجى اختيار ملف بامتداد csv",
  readFailed: "تعذّرت قراءة الملف",
  unknownColumns: (names: string) => `أعمدة غير مستعملة: ${names}`,
  alreadyImported: (on: string, by: string) => `تم استيراد نفس الملف في ${on} بواسطة ${by}`,
  rowsReady: (count: number) => `${count} سطراً جاهزاً`,
  rowsBlocked: (count: number) => `${count} سطراً يحتاج تصحيحاً`,
  rowsSkipped: (count: number) => `${count} سطراً متروكاً`,
  listSeparator: "، ",
  noticeSeparator: " · ",
  columnRow: "السطر",
  columnName: "الاسم الكامل",
  columnPhone: "الهاتف",
  columnVillage: "القرية",
  columnAge: "العصر",
  columnPaid: "دفع",
  columnMethod: "طريقة الدفع",
  columnAmount: "المبلغ",
  columnSkip: "اتركه",
  bulkTitle: "تعبئة جماعية",
  bulkAgeGroup: "أعطِ العصر للسطور المحددة",
  bulkApply: "طبّق",
  bulkSelectAllBlocked: "حدد كل ما ينقصه عصر",
  bulkClear: "ألغِ التحديد",
  bulkSelected: (count: number) => `${count} محدد`,
  selectRow: "تحديد السطر",
  skipRow: "اترك هذا السطر",
  matchPhone: (name: string) => `حساب موجود بنفس الرقم: ${name}`,
  matchName: (name: string) => `قد يكون: ${name}`,
  back: "رجوع",
  importAll: "استورد",
  importBlocked: "صحّح السطور المعلّمة قبل الاستيراد",
  nothingToImport: "لا يوجد سطر للاستيراد",
  amountHint: "اتركه فارغاً ليُسجّل مبلغ الاشتراك",
} as const;
