export const mvpVote = {
  needsRoster: "يحتاج الفريقان إلى لاعبين مسجَّلين في التشكيلة لبدء التصويت",
  needsResult: "سجّل نتيجة المباراة أولاً لتفتح التصويت",
  pickCandidates: "اختر 2 إلى 6 مرشحين لأفضل لاعب في المباراة",
  pickAtLeastTwo: "اختر لاعبين على الأقل",
  minutesLabel: "مدة التصويت بالدقائق",
  minutesHint: (minutes: number) => `المدة المعتمدة في البطولة ${minutes} دقيقة`,
  start: (count: number) => `بدء التصويت (${count})`,
  open: "التصويت مفتوح",
  closed: "التصويت مغلق",
  closesIn: (text: string) => `يغلق بعد ${text}`,
  endedAt: "انتهت مدة التصويت",
  close: "إغلاق التصويت",
  reopen: "إعادة فتحه",
  extend: "تمديد",
  extendMinutes: "دقائق إضافية",
  remove: "حذف",
  confirmRemove: "حذف هذا التصويت نهائياً؟ ستُحذف كل الأصوات المسجَّلة.",
  totalVotes: (count: number) => `مجموع الأصوات: ${count}`,
  winnerApplied: (name: string) => `${name} هو رجل المباراة بحسب التصويت`,
  tie: "تعادل التصويت، اختر رجل المباراة يدوياً",
  hours: (n: number) => `${n} ساعة`,
  minutes: (n: number) => `${n} دقيقة`,
} as const;
