export const playersTab = {
  added: "أُضيف اللاعب",
  confirmRemove: (name: string) => `إزالة ${name} من البطولة؟`,
  removed: "أُزيل اللاعب",
  heading: (count: number) => `اللاعبون (${count})`,
  empty: "لا يوجد لاعبون بعد — أضف أول لاعب أدناه.",
  joinRequest: "طلب انضمام",
  accepted: "قُبل اللاعب",
  acceptJoin: "قبول الانضمام",
  removeOf: (name: string) => `إزالة ${name}`,
  openCardOf: (name: string) => `فتح بطاقة ${name}`,
  addPlayer: "إضافة لاعب",
  allAdded: "كل المسجلين في النشاط مضافون بالفعل.",
  searchPlaceholder: "بحث بالاسم أو الهاتف...",
  pickPlayerLabel: "اختيار اللاعب",
  pickPlayer: "اختر لاعباً...",
  add: "إضافة",
} as const;
