export const proofUpload = {
  uploadFailed: "فشل رفع الصورة",
  connectionLost: "انقطع الاتصال بالإنترنت أثناء الرفع",
  tooSlow: "استغرق الرفع وقتاً طويلاً — تحقق من اتصالك",
  unexpected: "خطأ غير متوقع",
  label: "صورة تأكيد الدفع (كابتير)",
  imageAlt: "الكابتير",
  uploading: (percent: number) => `جاري الرفع... ${percent}%`,
  preparing: "جاري تجهيز الصورة...",
  uploaded: "تم رفع الصورة",
  retry: "إعادة المحاولة",
  hint: "JPG / PNG / WEBP — حجم أقصى 10 ميغابايت",
  takePhoto: "التقط صورة",
  pickFromGallery: "اختر من المعرض",
} as const;
