export const matchDisplay = {
  unknownScorer: "مجهول",
  ownGoal: "ع",
  penaltyShort: "ج",
  extraTimeShort: "و.إ",
  penalties: "ركلات ترجيح",
  motm: "رجل المباراة",
  priorMeetings: "مواجهات سابقة:",
  upcomingShort: "قادمة",
  todayMatches: "مباريات اليوم",
  clubName: "رابطة شباب قرية التاكلالت",
  shareResult: "مشاركة النتيجة",
  timeline: "مجريات المباراة",
  hideTimeline: "إخفاء المجريات",
} as const;

export const publicTournament = {
  standings: "الترتيب",
  bracket: "الدور الإقصائي",
  matches: "المباريات",
  upcoming: "مباريات قادمة",
  results: "النتائج",
  stats: "الإحصائيات",
  scorers: "الهدافون",
  discipline: "الانضباط",
  defence: "أفضل دفاع",
  motm: "رجل المباراة",
  teams: "الفرق",
  players: "اللاعبون",
  group: "مجموعة",
  noGroup: "بدون مجموعة",
  noMatchesYet: "لم تُحدَّد المباريات بعد",
  noTeamsYet: "لم تُحدَّد الفرق بعد",
  noPlayersYet: "لم يُحدَّد اللاعبون بعد",
} as const;
