import { lists } from "./lists";

import { countedNoun, PLAYERS, type NounForms } from "../arabicPlural";

const UNKNOWN_MINUTE_GOALS: NounForms = {
  one: "هدف دون دقيقة مسجلة",
  two: "هدفان دون دقيقة مسجلة",
  few: "أهداف دون دقيقة مسجلة",
  many: "هدفاً دون دقيقة مسجلة",
  other: "هدف دون دقيقة مسجلة",
};

export const matchDisplay = {
  tieUnresolved: "متساويان تماماً — يفصل بينهما القرعة",
  tieMark: "قرعة",
  forfeitBadge: "انسحاب",
  unknownScorer: "مجهول",
  unknownMinute: (count: number) => countedNoun(count, UNKNOWN_MINUTE_GOALS),
  unknownMinuteTally: (count: number) => `×${count}`,
  ownGoal: "ع",
  penaltyShort: "ج",
  extraTimeShort: "و.إ",
  penalties: "ركلات ترجيح",
  motm: "رجل المباراة",
  priorMeetings: "مواجهات سابقة:",
  meetingSeparator: lists.separator,
  upcomingShort: "قادمة",
  todayMatches: "مباريات اليوم",
  clubName: "رابطة شباب قرية التاكلالت",
  shareResult: "مشاركة النتيجة",
  timeline: "مجريات المباراة",
  hideTimeline: "إخفاء المجريات",
} as const;

export const publicTournament = {
  standings: "الترتيب",
  bracket: "الدور الإقصائي",
  matches: "المباريات",
  upcoming: "مباريات قادمة",
  results: "النتائج",
  stats: "الإحصائيات",
  scorers: "الهدافون",
  discipline: "الانضباط",
  defence: "أفضل دفاع",
  motm: "رجل المباراة",
  entrant: {
    team: {
      plural: "الفرق",
      column: "الفريق",
      noneYet: "لم تُحدَّد الفرق بعد",
      bracketWaitingHint: "تُحدَّد فرق الدور الإقصائي من ترتيب المجموعات بعد انتهاء دور المجموعات",
      followed: "تتابع الفريق الآن",
      unfollowed: "توقفت عن متابعة الفريق",
      follow: "تابع",
      following: "متابَع",
    },
    player: {
      plural: "اللاعبون",
      column: "اللاعب",
      noneYet: "لم يُحدَّد اللاعبون بعد",
      bracketWaitingHint:
        "يُحدَّد لاعبو الدور الإقصائي من ترتيب المجموعات بعد انتهاء دور المجموعات",
      followed: "تتابع اللاعب الآن",
      unfollowed: "توقفت عن متابعة اللاعب",
      follow: "تابع",
      following: "متابَع",
    },
  },
  standingsColumns: {
    rank: "#",
    points: "نقاط",
    played: "لعب",
    won: "فاز",
    drawn: "تعادل",
    lost: "خسر",
    goalsFor: "له",
    goalsAgainst: "عليه",
    goalDifference: "الفرق",
  },
  group: "مجموعة",
  noGroup: "بدون مجموعة",
  noMatchesYet: "لم تُحدَّد المباريات بعد",
  noPlayers: "لا يوجد لاعبون بعد",
  playerCount: (count: number) => countedNoun(count, PLAYERS),
  captain: "القائد",
  teamDecidedLater: "يُحدد لاحقاً",
  bye: "بلا خصم",
  byeNote: "يمرّ إلى الدور التالي",
  bracketRound: (round: number) => `الدور ${round}`,
} as const;
