export const quizScores = {
  reopened: "أعيد فتح الأسئلة الفائتة",
  roundRestored: "أرجعت نقاط الجولة",
  roundVoided: "ألغيت نقاط الجولة",
  allRoundsRestored: "أرجعت نقاط كل الجولات",
  allRoundsVoided: "ألغيت نقاط كل الجولات",
  title: "نقاط المشاركين",
  round: "الجولة",
  nobodyPlayed: "لم يشارك أحد في هذه الجولة",
  notStarted: "لم تبدأ هذه الجولة بعد",
  voidedMark: "· ملغاة",
  reopenTitle: "إعادة فتح الأسئلة الفائتة",
  reopen: "إعادة فتح",
  restore: "إرجاع",
  void: "إلغاء",
  roundPoints: (action: string, name: string) => `${action} نقاط ${name} في هذه الجولة`,
  allRoundsPoints: (action: string, name: string) => `${action} نقاط ${name} في كل الجولات`,
  allRounds: "الكل",
  thisRound: "الجولة",
  openAttempt: (name: string) => `محاولة ${name}`,
} as const;
