export const seriesResult = {
  heading: (parts: string) => `${parts} المباراة`,
  none: (parts: string) => `لم تُسجَّل ${parts} بعد`,
  partNumber: (word: string, order: number) => `${word} ${order}`,
  abandoned: "متوقفة",
  won: "فوز",
  drawn: "تعادل",
  wonBy: (name: string) => `فوز ${name}`,
  outcomeLabel: "نتيجة الجولة",
  pickOutcome: "اختر النتيجة...",
  pointsOf: (name: string) => `نقاط ${name}`,
  add: "إضافة",
  save: "حفظ",
  cancel: "إلغاء",
  edit: "تعديل",
  remove: "حذف",
  standsAt: "الوضع الحالي",
  partsLeft: (parts: string) => `المتبقي ${parts}`,
  endsAt: (parts: string) => `تنتهي المباراة عند ${parts}`,
  endsWhenAllPlayed: "تنتهي المباراة بلعب كل الجولات",
  over: "انتهت المباراة",
  level: "تعادل",
  inProgress: "قيد اللعب",
  extending: "تعادلت، وتُمدَّد بجولتين",
  wonThe: (name: string) => `فازت ${name}`,
  colourOf: (name: string, colour: string) => `${name} ${colour}`,
  loadFailed: "تعذّر تحميل جولات المباراة",
  notConfigured: "أكمل إعداد جولات البطولة من تبويب التفاصيل قبل تسجيل نتيجة",
} as const;
