export const seriesResult = {
  heading: "وحدات المباراة",
  matchResult: "نتيجة المباراة",
  recordResult: "تسجيل النتيجة",
  resultRow: "النتيجة",
  none: "لم تُسجَّل وحدات بعد",
  unitNumber: (word: string, order: number) => `${word} ${order}`,
  abandoned: "متوقفة",
  endedBy: (name: string) => `أنهتها ${name}`,
  drawn: "تعادل",
  wonBy: (name: string) => `فوز ${name}`,
  outcomeOf: (word: string) => `نتيجة ${word}`,
  pickOutcome: "اختر النتيجة...",
  pointsOf: (name: string) => `نقاط ${name}`,
  add: "إضافة",
  addOne: (word: string) => `إضافة ${word}`,
  openOne: (word: string) => `فتح ${word}`,
  closeOne: (word: string) => `طي ${word}`,
  openDiscards: "تسجيل وحدات داخل هذه الوحدة يلغي نتيجتها المكتوبة",
  openAnyway: "متابعة",
  countedTwice: (worth: string) => `تُحتسب ${worth}`,
  decidingUnit: "الوحدة الحاسمة",
  save: "حفظ",
  cancel: "إلغاء",
  edit: "تعديل",
  remove: "حذف",
  unitsLeft: (units: string) => `المتبقي ${units}`,
  endsAt: (units: string) => `تنتهي المباراة عند ${units}`,
  endsWhenAllPlayed: "تنتهي المباراة بلعب كل الوحدات",
  over: "انتهت المباراة",
  takesNoMore: "لا تقبل وحدات أخرى",
  level: "تعادل",
  inProgress: "قيد اللعب",
  extending: (units: string) => `تعادلت، وتُمدَّد ب${units}`,
  extendingByDecider: "تعادلت، وتُلعب وحدة حاسمة",
  wonThe: (name: string) => `فازت ${name}`,
  colourOf: (name: string, colour: string) => `${name} ${colour}`,
  moves: "الحركات",
  moveOf: (name: string, side: string) => `${name} من ${side}`,
  moveEffect: (name: string, gained: string, lost: string) =>
    `${name} تضيف ${gained} وتخصم ${lost}`,
  moveWorth: (name: string, worth: string) => `${name} تُحتسب بـ${worth}`,
  movesSeparator: "، ",
  recordMove: "تسجيل حركة",
  pickMove: "اختر الحركة...",
  pickSide: "اختر الطرف...",
  pickUnit: "الوحدة التي تقع عليها الحركة",
  pickUnitPrompt: "اختر الوحدة...",
  undoMove: "تراجع",
  noMoves: "لا حركات معرّفة في هذه البطولة",
  loadFailed: "تعذّر تحميل جولات المباراة",
  notConfigured: "أكمل إعداد مستويات البطولة من تبويب التفاصيل قبل تسجيل نتيجة",
} as const;
