export const signUp = {
  title: "إنشاء حساب",
  stepCredentials: "رقم الهاتف وكلمة المرور",
  stepPerson: "من أنت",
  passwordLabel: "كلمة المرور",
  confirmLabel: "تأكيد كلمة المرور",
  passwordPlaceholder: "••••••••",
  photoLabel: "الصورة الشخصية (اختياري)",
  next: "التالي",
  back: "السابق",
  submit: "إنشاء الحساب",
  submitting: "جاري الإنشاء...",
  haveAccount: "لديك حساب؟",
  signIn: "تسجيل الدخول",
  passwordMismatch: "كلمتا المرور غير متطابقتين",
} as const;
