export const teamsTab = {
  confirmDelete: "هل تريد حذف هذا الفريق؟",
  ungrouped: (count: number) => `فرق بدون مجموعة (${count})`,
  pickGroup: "اختر مجموعة...",
  teamCount: (count: number) => `عدد الفرق: ${count}`,
  save: "حفظ",
  cancel: "إلغاء",
  deleteTeam: "حذف الفريق",
  teamLogo: "شعار الفريق",
  noGroup: "بدون مجموعة",
  noPlayers: "لا يوجد لاعبون بعد",
  awaitingApproval: "بانتظار الموافقة",
  accept: "قبول",
  reject: "رفض",
  remove: "إزالة",
  pickPlayer: "اختر لاعباً...",
  add: "إضافة",
  addPlayer: "إضافة لاعب",
  newTeamName: "اسم الفريق الجديد",
  team: "فريق",
  unassigned: (count: number) => `لاعبون غير مصنّفين (${count})`,
} as const;
