import { countedNoun, PLAYERS } from "../arabicPlural";

export const teamsTab = {
  confirmDelete: "هل تريد حذف هذا الفريق؟",
  teamCount: (count: number) => `عدد الفرق: ${count}`,
  save: "حفظ",
  cancel: "إلغاء",
  deleteTeam: "حذف الفريق",
  teamLogo: "شعار الفريق",
  renameTeam: "تعديل اسم الفريق",
  rosterOf: (count: number, size: number) => `${count} / ${size}`,
  rosterCount: (count: number) => countedNoun(count, PLAYERS),
  awaitingCount: (count: number) => `${count} بانتظار الموافقة`,
  captainBadge: (name: string) => `القائد ${name}`,
  makeCaptain: (name: string) => `اجعل ${name} قائد الفريق`,
  clearCaptain: (name: string) => `إلغاء قيادة ${name} للفريق`,
  noPlayers: "لا يوجد لاعبون بعد",
  awaitingApproval: "بانتظار الموافقة",
  acceptOf: (name: string) => `قبول ${name}`,
  rejectOf: (name: string) => `رفض ${name}`,
  removeOf: (name: string) => `إزالة ${name}`,
  renameOf: (name: string) => `تعديل اسم ${name}`,
  pickPlayer: "اختر لاعباً...",
  add: "إضافة",
  addPlayer: "إضافة لاعب",
  newTeamName: "اسم الفريق الجديد",
  team: "فريق",
  unassigned: (count: number) => `لاعبون غير مصنّفين (${count})`,
} as const;
